/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

char findTheDifference(char* s, char* t) {
    char alphabetic[] = "abcdefghijklmnopqrstuvwxyz";
    int alphabet_idx[26] = {0};
    int alphabet_idx2[26] = {0};
    char diff_t;
    
    for (int i = 0; t[i] != '\0'; i++) {
        char *res = strchr(alphabetic, t[i]);
        if (res != NULL) {
            int index = res - alphabetic;
            alphabet_idx[index]++; 
        } else {
            continue;
        }
    }
    for (int i = 0; s[i] != '\0'; i++) {
        char *res2 = strchr(alphabetic, s[i]);
        if (res2 != NULL) {
            int index2 = res2 - alphabetic;
            alphabet_idx2[index2]++; 
        } else {
            continue;
        }
    }

    for (int i = 0; i < 26; i++) {
        if (alphabet_idx[i] != alphabet_idx2[i]) {
            diff_t = alphabetic[i];
            break;
        }
    }

    return diff_t;
}

int main(void) {
    char *s = "";
    char *t = "y";

    printf("%c\n", findTheDifference(s, t));
}
